channels:
  - conda-forge
  - default
dependencies:
  # NOTE: issue with django 3 and django-haystack:
  # haystack/utils/__init__.py", line 9
  # from django.utils import six
  # ImportError: cannot import name 'six' from 'django.utils'
  - django >=2,<3
  - djangorestframework
  - django-haystack
  - factory_boy
  - python>=3.8
  # development
  - black
  - docker-compose
  - flake8
  - mypy
  - pip
  - pre-commit
  - pip:
    - django-extensions
    - drf-haystack
    - elasticsearch>=5,<6
    - elasticsearch-dsl>=5.0.0,<6.0.0
