version: '3'
services:

  djangopoc:
    # only for debugging
    stdin_open: true
    tty: true

    image: djangopoc:${PYTHON_VERSION:-3.7}
    env_file:
      - ./.env
    volumes:
      - /tmp/djangopoc:/tmp
      - ..:/djangopoc
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.7}
    depends_on:
      - elasticsearch
    command: |
      bash ./docker/runserver.sh
    ports:
      - 48000:48000

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 49200:9200

volumes:
  elasticsearch_data:
